name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: 54.173.43.130 # Your server's IP address
          username: ubuntu # Your server's username
          port: 3002
          key: ${{ secrets.PRIVATE_SSH_KEY }} # Your server's SSH private key
          script: |
            ls 
            whoami
            echo "success boizzz"
            cd /home/ubuntu/nextjsproject # Specify the path to your app directory on the server
            git pull
            npm install
            npm run build
            pm2 restart your-pm2-service-name # Replace with your PM2 service name